<header>
	<nav class="navbar navbar-expand-sm bg-light navbar-light">
		<!-- Brand/logo -->
		<a class="navbar-brand" href="#"> <img src="/images/logo_home.png" alt="logo"
			style="width: 40px;">
		</a>

		<!-- Links -->
		<ul class="navbar-nav">
			<li id="li_timetable" class="nav-item"><a class="nav-link"
					href="timetable.jsp">Horários</a></li>
				<li id="li_stations" class="nav-item"><a class="nav-link"
					href="stations.jsp">Estações</a></li>
				<li id="li_paths" class="nav-item"><a class="nav-link"
					href="paths.jsp">Rotas</a></li>
				<li id="li_holidays" class="nav-item"><a class="nav-link"
					href="holidays.jsp">Feriados</a></li>
				<li id="li_users" class="nav-item"><a class="nav-link"
					href="users.jsp">Usuários</a></li>
					
		</ul>
		
		<ul class="navbar-nav ml-auto">
            <li class="nav-item">
        	<button class="btn btn-info btn-sm "  onclick="location.href='login.jsp';">Sair</button>
            </li>
        </ul>
	</nav>
</header>